sonar.projectKey=psw-pipeline-base
sonar.projectName=PSW Pipeline Base
sonar.projectVersion=0.0.1-SNAPSHOT

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.source=17
sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/model/**,**/*Application.java,**/dto/**
sonar.coverage.exclusions=**/model/**,**/*Application.java

sonar.sourceEncoding=UTF-8
